# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :staging_build do
    increment_build_number_in_list(xcodeproj: './FastlaneDemo.xcodeproj', target: 'FastlaneDemo')
    gym(scheme: 'FastlaneDemo', workspace: './FastlaneDemo.xcworkspace')
  end

  lane: beta do
    staging_build
    upload_to_testflight(username: 'haquangtrong.ton@gmail.com', app_identifier: 'FastlaneDemo')
    commit_version_bump(message: 'bump build')
    
end
